# Generated by Django 3.0.8 on 2020-08-17 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GDT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=255, null=True)),
                ('quantidade_vagas', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='petiano',
            options={'ordering': ['pet']},
        ),
        migrations.RemoveField(
            model_name='petiano',
            name='pet_extenso',
        ),
        migrations.RemoveField(
            model_name='petiano',
            name='pet_sigla',
        ),
        migrations.RemoveField(
            model_name='petiano',
            name='user',
        ),
        migrations.AddField(
            model_name='petiano',
            name='credenciado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='petiano',
            name='email',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='petiano',
            name='nome',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='petiano',
            name='pet',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='petiano',
            name='telefone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='petiano',
            name='gdt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gdt_do_petiano', to='evento.GDT'),
        ),
    ]
