# Generated by Django 3.0.8 on 2020-08-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0002_auto_20200817_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='gdt',
            name='descricao',
            field=models.TextField(null=True),
        ),
    ]
