# Generated by Django 3.0.8 on 2020-09-15 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0003_gdt_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='gdt',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
