# Generated by Django 3.0.8 on 2021-05-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0004_gdt_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='petiano',
            name='acessibilidade',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='petiano',
            name='descricao_acessibilidade',
            field=models.CharField(default='', max_length=255),
        ),
    ]
