# Generated by Django 3.0.14 on 2021-05-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0005_auto_20210507_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petiano',
            name='descricao_acessibilidade',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
